name: MySQL CI

on:
  push:
    branches:
      - main  # Adapte para o branch que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword

    steps:
      - uses: actions/checkout@v2

      - name: Run MySQL scripts
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        run: |
          sudo apt-get install mysql-client
          mysql -h 127.0.0.1 -u root -prootpassword -e "source sql/queries.sql"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: my-feature-branch  # Nome do branch que será criado
          base: main  # Branch base para o pull request
          title: 'Automatic Pull Request'
          body: |
            This pull request is automatically created by GitHub Actions.
            - [ ] Review changes
            - [ ] Approve and merge
